nameOverride: ''
fullnameOverride: ''
image:
  repository: ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher
  pullPolicy: Always
  tag: 0.0.1
imagePullSecrets: []
farEdgeKubelet:
  image:
    repository: ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet
    pullPolicy: Always
    tag: 0.0.2
  initScript:
    timeoutSeconds: 120
    retryIntervalSeconds: 5
    logLevel: 0
  registry:
    url: ''
    insecure: false
    plainHTTP: false
    overrideRegistry: false
    overrideDefaultRegistry: false
    registryPullSecret: ''
    registryUsername: ''
    registryPassword: ''
    localRegistry: /var/tmp/vk-embserve
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ''
clusterRole:
  extraRules: []
role:
  extraRules: []
mqttBroker:
  host: ''
  port: 1883
  clientId: far-edge-node-watcher
  serverTLS: false
  mutualTLS: false # this is an upgrade over the previous
podAnnotations: {}
podLabels: {}
podSecurityContext:
  fsGroup: 2000
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
resources: {}
livenessProbe: {}
readinessProbe: {}
nodeSelector: {}
tolerations: []
affinity: {}
