nameOverride: ''
fullnameOverride: ''
image:
  repository: harbor.nbfc.io/mlsysops/fita/far-edge-node-watcher
  pullPolicy: Always
  tag: 0.0.1
imagePullSecrets: []
farEdgeKubelet:
  image:
    repository: ghcr.io/fraunhoferportugal/fita/components/far-edge-kubelet
    pullPolicy: IfNotPresent
    tag: 0.0.1
  registry:
    url: harbor.nbfc.io
    insecure: false
    plainHTTP: false
    overrideRegistry: false
    overrideDefaultRegistry: true
    registryPullSecret: ''
    registryUsername: ''
    registryPassword: ''
    localRegistry: /var/tmp/vk-embserve
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ''
clusterRole:
  extraRules: []
role:
  extraRules: []
mqttBroker:
  host: ''
  port: 1883
  clientId: far-edge-node-watcher
podAnnotations: {}
podLabels: {}
podSecurityContext:
  fsGroup: 2000
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
resources: {}
livenessProbe: {}
readinessProbe: {}
nodeSelector: {}
tolerations: []
affinity: {}
