# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: far-edge-node-watcher

builds:
  - skip: true

dockers:
  - id: develpment-amd64
    build_flag_templates:
      - --platform=linux/amd64
    image_templates:
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Env.Summary }}-amd64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Env.Branch }}-amd64
    extra_files:
      - nextgengw/main.py
    dockerfile: Dockerfile
    use: buildx
  - id: develpment-arm64
    build_flag_templates:
      - --platform=linux/arm64
    image_templates:
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Env.Summary }}-arm64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Env.Branch }}-arm64
    extra_files:
    - nextgengw/main.py
    dockerfile: Dockerfile
    use: buildx
  - id: develpment-armv7
    build_flag_templates:
      - --platform=linux/arm/v7
    image_templates:
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Env.Summary }}-arm-v7
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Env.Branch }}-arm-v7
    extra_files:
      - nextgengw/main.py
    dockerfile: Dockerfile
    use: buildx

docker_manifests:
  - id: development
    name_template: gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Env.Branch }}
    image_templates:
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Env.Summary }}-amd64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Env.Summary }}-arm64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Env.Summary }}-arm-v7

checksum:
  disable: true

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

release:
  disable: true

announce:
  skip: true
