# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: far-edge-node-watcher


builds:
  - skip: true

dockers:
  - id: main-amd64
    build_flag_templates:
      - --platform=linux/amd64
    image_templates:
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:latest-amd64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Tag }}-amd64
    extra_files:
      - nextgengw/main.py
    dockerfile: Dockerfile
    use: buildx
  - id: main-arm64
    build_flag_templates:
      - --platform=linux/arm64
    image_templates:
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:latest-arm64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Tag }}-arm64
    extra_files:
      - nextgengw/main.py
    dockerfile: Dockerfile
    use: buildx
  - id: main-arm
    build_flag_templates:
      - --platform=linux/arm/v7
    image_templates:
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:latest-arm-v7
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Tag }}-arm-v7
    extra_files:
      - nextgengw/main.py
    dockerfile: Dockerfile
    use: buildx

docker_manifests:
  - id: tag
    name_template: ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Tag }}
    image_templates:
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Tag }}-amd64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Tag }}-arm64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Tag }}-arm-v7
  - id: latest
    name_template: ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:latest
    image_templates:
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Tag }}-amd64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Tag }}-arm64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Tag }}-arm-v7
  - id: major
    name_template: ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Major }}
    image_templates:
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Tag }}-amd64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Tag }}-arm64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Tag }}-arm-v7
  - id: minor
    name_template: 'ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Major }}.{{ .Minor }}'
    image_templates:
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Tag }}-amd64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Tag }}-arm64
      - ghcr.io/fraunhoferportugal/fita/components/far-edge-node-watcher:{{ .Tag }}-arm-v7

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: fraunhoferportugal
    name: far-edge-node-watcher
  draft: true
