# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: far-edge-node-watcher


builds:
  - skip: true

dockers:
  - id: main-amd64
    build_flag_templates:
      - --platform=linux/amd64
    image_templates:
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:latest-amd64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-amd64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Major }}-amd64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Major }}.{{ .Minor }}-amd64
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:latest-amd64
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-amd64
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Major }}-amd64
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Major }}.{{ .Minor }}-amd64
    extra_files:
      - nextgengw/main.py
    dockerfile: Dockerfile
    use: buildx
  - id: main-arm64
    build_flag_templates:
      - --platform=linux/arm64
    image_templates:
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:latest-arm64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Major }}-arm64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Major }}.{{ .Minor }}-arm64
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:latest-arm64
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm64
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Major }}-arm64
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Major }}.{{ .Minor }}-arm64
    extra_files:
      - nextgengw/main.py
    dockerfile: Dockerfile
    use: buildx
  - id: main-arm
    build_flag_templates:
      - --platform=linux/arm/v7
    image_templates:
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:latest-arm
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm-v7
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Major }}-arm-v7
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Major }}.{{ .Minor }}-arm-v7
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:latest-arm
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm-v7
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Major }}-arm-v7
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Major }}.{{ .Minor }}-arm-v7
    extra_files:
      - nextgengw/main.py
    dockerfile: Dockerfile
    use: buildx

docker_manifests:
  - id: main-gitea-tag
    name_template: gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}
    image_templates:
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-amd64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm-v7
  - id: main-registry-tag
    name_template: registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}
    image_templates:
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-amd64
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm64
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm-v7
  - id: main-gitea-latest
    name_template: gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:latest
    image_templates:
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-amd64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm-v7
  - id: main-registry-latest
    name_template: registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:latest
    image_templates:
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-amd64
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm64
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm-v7
  - id: main-gitea-major
    name_template: gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Major }}
    image_templates:
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-amd64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm-v7
  - id: main-registry-major
    name_template: registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Major }}
    image_templates:
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-amd64
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm64
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm-v7
  - id: main-gitea-minor
    name_template: gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Major }}{{ .Minor }}
    image_templates:
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-amd64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm64
      - gitea.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm-v7
  - id: main-registry-minor
    name_template: registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Major }}{{ .Minor }}
    image_templates:
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-amd64
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm64
      - registry.lab.fraunhofer.pt/fita/far-edge-node-watcher:{{ .Tag }}-arm-v7

checksum:
  split: true

archives:
  - id: binaries
    formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  gitea: {}

gitea_urls:
  api: https://gitea.lab.fraunhofer.pt/api/v1
  download: https://gitea.lab.fraunhofer.pt
