name: Development builds

on:
  push:
    branches:
      - 'feature/**'
      - 'feat/**'
      - 'fix/**'
      - 'hotfix/**'
      - development

jobs:
  build-and-publish-dev-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: ~1.23

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: gitea.lab.fraunhofer.pt          
          username: ${{ vars.ACTIONS_USER }}        # Only needed in Gitea
          password: ${{ secrets.ACTIONS_TOKEN }}    #   Github generates a token by workflow run, ${{ GITHUB_TOKEN }}, that can be used with the ${{ github.repository_owner }} user
                                                    #   An "actions" user is responsible by pushing to the package
      
      - name: Get tag-safe branch name and develpment tag
        id: get_metadata
        run: |
          # any shell command whose output you want to capture
          VERSION=$(make version)
          echo "Tag Name: $VERSION"
          echo "summary=$VERSION" >> $GITHUB_OUTPUT
          BRANCH=$(make branch)
          echo "Image tag safe branch name: $BRANCH"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "2.9.0"
          args: --config .goreleaser-dev.yaml --skip validate --clean
        env:
          Branch: ${{ steps.get_metadata.outputs.branch }}
          Summary: ${{ steps.get_metadata.outputs.summary }}
