name: Validate

on:
  workflow_call:

  pull_request:
    branches:
      - master
      - development
  push:
    branches:
      - development

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint code and check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Missing linter"

  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - run: |
          echo "Missing test framework"
      - name: Publish coverage dir as an artifact
        run: |
          echo "Missing coverage"
        # uses: christopherhx/gitea-upload-artifact@v4
        # with:
        #   name: coverage
        #   path: |
        #     ./coverage

      - name: Publish coverage html report
        run: |
          echo "Missing coverage report"
        # uses: christopherhx/gitea-upload-artifact@v4
        # with:
        #   name: coverage-report
        #   path: |
        #     ./coverage/merged.html
