apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "far-edge-kubelet.fullname" . }}
  labels:
    {{- include "far-edge-node-watcher.labels" . | nindent 4 }}
rules:
  # Kubelet certificate management
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests"]
    verbs: ["create", "get", "list", "watch", "delete", "update"]
  
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests/approval"]
    verbs: ["update"]

  - apiGroups: ["certificates.k8s.io"]
    resources: ["signers"]
    resourceNames: ["kubernetes.io/kubelet-serving"]
    verbs: ["approve"]

  # Kubelet
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "services"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "get", "list", "watch", "patch"]

  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["create", "get", "update", "delete"]

  - apiGroups: [""]
    resources: ["nodes/status"]
    verbs: ["update", "patch"]

  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["update", "patch"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]

  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
