apiVersion: v1
kind: ConfigMap
metadata:
  name: far-edge-kubelet-certificate-request-script
data:
  generate-cert.sh: |
    #!/bin/bash

    set -e
    LOG_LEVEL={{ .Values.farEdgeKubelet.initScript.logLevel }}
    TIMEOUT={{ .Values.farEdgeKubelet.initScript.timeoutSeconds }}    # in seconds 
    RETRY_INTERVAL={{ .Values.farEdgeKubelet.initScript.retryIntervalSeconds }}    # in seconds

    NAMESPACE="${NAMESPACE:-default}"
    CSR_NAME="$NODE_NAME-far-edge-kubelet-serving-cert"
    CERT_DIR="/etc/certificates"

    mkdir -p $CERT_DIR

    if (( LOG_LEVEL > 0)); then
        echo "Generating private key and CSR..."
    fi
    openssl ecparam -name prime256v1 -genkey -noout -out $CERT_DIR/cert.key
    openssl req -new -key $CERT_DIR/cert.key -nodes -out $CERT_DIR/cert.csr \
        -subj "/CN=system:node:${NODE_NAME}/O=system:nodes" \
        -addext "subjectAltName = IP:$POD_IP, DNS:$NODE_NAME.$NAMESPACE, DNS:$NODE_NAME.$NAMESPACE.svc"

    CSR_BASE64=$(cat $CERT_DIR/cert.csr | base64 | tr -d '\n')

    kubectl delete csr "$CSR_NAME" --ignore-not-found > /dev/null

    if (( LOG_LEVEL > 0)); then
        echo "Creating CSR object in Kubernetes..."
    fi
    kubectl apply -f - <<EOF > /dev/null
    apiVersion: certificates.k8s.io/v1
    kind: CertificateSigningRequest
    metadata:
      name: $CSR_NAME
    spec:
      request: $CSR_BASE64
      signerName: kubernetes.io/kubelet-serving
      usages:
      - key encipherment 
      - digital signature
      - server auth
    EOF

    kubectl certificate approve "$CSR_NAME" > /dev/null
    if (( LOG_LEVEL > 0)); then
        echo "Approved CSR"
    fi

    if (( LOG_LEVEL > 0)); then
        echo "Waiting for request to be signed and certificate populated..."
    fi

    for ((i = 1; i <= $((TIMEOUT / RETRY_INTERVAL)); i++)); do
        CERT=$(kubectl get csr "$CSR_NAME" -o jsonpath='{.status.certificate}')
        if [[ -n "$CERT" ]]; then
            if (( LOG_LEVEL > 0)); then
                echo "Certificate available"
            fi
            break
        fi

        if (( LOG_LEVEL > 0)); then
            echo "Waiting for certificate to be populated..."
        fi
        sleep $RETRY_INTERVAL
    done

    if [[ -z "$CERT" ]]; then
        echo "Kubelet certificate generation failed" >&2
        exit 1
    fi

    echo "$CERT" | base64 -d > $CERT_DIR/cert.crt
    if (( LOG_LEVEL > 0 )); then
        echo "Kubelet certificate generation completed."
    fi
    set +e
