apiVersion: v1
kind: ConfigMap
metadata:
  name: far-edge-kubelet-certificate-request-script
data:
  generate-cert.sh: |
    #!/bin/bash

    set -e
    LOG_LEVEL=1
    NAMESPACE="${NAMESPACE:-default}"
    CSR_NAME="$NODE_NAME-far-edge-kubelet-serving-cert"
    CERT_DIR="/etc/certificates"

    mkdir -p $CERT_DIR

    if (( LOG_LEVEL > 0)); then
        echo "Generating private key and CSR..."
    fi
    openssl ecparam -name prime256v1 -genkey -noout -out $CERT_DIR/cert.key
    openssl req -new -key $CERT_DIR/cert.key -nodes -out $CERT_DIR/cert.csr \
        -subj "/CN=system:node:${NODE_NAME}/O=system:nodes" \
        -addext "subjectAltName = IP:$POD_IP, DNS:$NODE_NAME.$NAMESPACE, DNS:$NODE_NAME.$NAMESPACE.svc"

    CSR_BASE64=$(cat $CERT_DIR/cert.csr | base64 | tr -d '\n')

    kubectl delete csr "$CSR_NAME" --ignore-not-found 

    if (( LOG_LEVEL > 0)); then
        echo "Creating CSR object in Kubernetes..."
    fi
    kubectl apply -f - <<EOF
    apiVersion: certificates.k8s.io/v1
    kind: CertificateSigningRequest
    metadata:
      name: $CSR_NAME
    spec:
      request: $CSR_BASE64
      signerName: kubernetes.io/kubelet-serving
      usages:
      - key encipherment 
      - digital signature
      - server auth
    EOF

    kubectl certificate approve "$CSR_NAME"
    if (( LOG_LEVEL > 0)); then
        echo "Approved CSR"
    fi

    if (( LOG_LEVEL > 0)); then
        echo "Waiting for request to be signed and certificate populated..."
    fi
    for _ in {1..120}; do
        CERT=$(kubectl get csr "$CSR_NAME" -o jsonpath='{.status.certificate}')

        if [[ -n "$CERT" ]]; then
            if (( LOG_LEVEL > 0)); then
                echo "Certificate available"
            fi
            echo "$CERT" | base64 -d > $CERT_DIR/cert.crt
            break
        fi

        if (( LOG_LEVEL > 0)); then
            echo "Waiting for certificate to be populated..."
        fi
        sleep 5
    done

    if (( LOG_LEVEL > 0 )); then
        echo "Kubelet certificate generation completed."
    fi

    if (( LOG_LEVEL > 0 )); then
        ls -la "$CERT_DIR"/cert.key "$CERT_DIR"/cert.crt
    fi
    set +e
