name: Test and Lint

on:
  workflow_call:

  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main
      - development

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint code and check formatting
    runs-on: self-hosted
    steps:
      - run: echo "Missing Linter"

  test:
    name: Test code
    runs-on: self-hosted
    steps:
      - run: echo "Missing tests"
